### PR TITLE
upgrade to 1.8

### PR DESCRIPTION
**Pull request by tbaum**
please check the delete + restart.

https://github.com/jexp/neo4j-clean-remote-db-addon/blob/upgrade-1.8/src/main/java/org/neo4j/server/extension/test/delete/DeleteDatabaseResource.java#L77

i'm not sure if it works that way  (so we can not replace the database.graph instance since it has only a getter now)

### CODE REVIEW

**Comment by pjvds** [comment]
Would love to see this pulled!

**Comment by pjvds** [comment]
Thx for the pull! It also would be helpful if you could also update the downloads.

**Comment by jexp** [comment]
done

**Comment by pjvds** [comment]
Awesome!

**Pull request merged**
